server:
  port: 8084

spring:
  config:
    activate:
      on-profile: prod

  jwt:
    secret: 9E6436E6EB6D3B111EBFC58691E53aaaaaaaaaaaaaaaabbbbb
    expiration: 360000000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-fitlog.c324sysukalg.ap-northeast-2.rds.amazonaws.com/YoonONi?serverTimezone=UTC&characterEncoding=UTF-8
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect


logging:
  config: classpath:logback-spring-local.xml

chatgpt:
  api-key : ${GPT_KEY}
  model : text-davinci-003
openai:
  url:
    model : https://api.openai.com/v1/models
    model-list : https://api.openai.com/v1/models/
    legacy-prompt : https://api.openai.com/v1/completions
    prompt : https://api.openai.com/v1/chat/completions

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl